version: "3"
services:
  nginx:
    image: registry.cn-shenzhen.aliyuncs.com/rain_sunshine_cloud/nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    links:
      - php
    volumes:
      - "./conf/nginx:/etc/nginx/conf.d"
      - "./app:/data/nginx/web/"
      - "./log/nginx:/data/nginx/log/"
    container_name: nginx
    hostname: nginx
  php:
    image: registry.cn-shenzhen.aliyuncs.com/rain_sunshine_cloud/php
    volumes:
      - "./log/php:/data/php/log"
      - "./app:/data/nginx/web"
      - "./conf/php/php.ini:/usr/local/etc/php/php.ini"
      - "./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.d/docker.conf"
      - "./app:/app"
    depends_on:
      - mysql
      - redis
    container_name: php
    links:
      - mysql
      - redis
    hostname: php
  mysql:
   image: mysql
   ports:
      - "3307:3306"
   volumes:
      - "./conf/mysql:/etc/mysql/conf.d"
      - "./data/mysql:/var/lib/mysql"
   environment:
      -  MYSQL_ROOT_PASSWORD=12
   container_name: mysql
   hostname: mysql
  redis:
   image: redis
   ports:
     - "6379:6379"
   volumes:
    - "./conf/redis/redis.conf:/usr/local/etc/redis.conf"
   command: ["redis-server","/usr/local/etc/redis.conf"]
   container_name: redis
   hostname: redis
